function [ ] = SR_by_LBF(par, sr_image, bicubic_image, landmarks, dataset_landmarks, mean_hr)
%SR_BY_LBF Summary of this function goes here
%   Detailed explanation goes here

patched_image = sr_image;

% Find the images and regions from the datasets that best match the facial
% landmarks for a specific facial component of the input image

% 1) Mouth Region
mouth_features = ["mouth_left_corner",...
                  "mouth_upper_lip_left_contour1",...
                  "mouth_upper_lip_left_contour2",...
                  "mouth_upper_lip_left_contour3",...
                  "mouth_upper_lip_top",...
                  "mouth_upper_lip_bottom",...
                  "mouth_upper_lip_right_contour3",...
                  "mouth_upper_lip_right_contour2",...
                  "mouth_upper_lip_right_contour1",...
                  "mouth_right_corner",...
                  "mouth_lower_lip_right_contour1",...
                  "mouth_lower_lip_right_contour2",...
                  "mouth_lower_lip_right_contour3",...
                  "mouth_lower_lip_top",...
                  "mouth_lower_lip_bottom",...
                  "mouth_lower_lip_left_contour3",...
                  "mouth_lower_lip_left_contour2",...
                  "mouth_lower_lip_left_contour1"];

[mouth_patch, ~, coords] = Get_SR_Patch(sr_image, mouth_features, landmarks, dataset_landmarks, 2, 5);
patched_image(coords(3):coords(4),coords(1):coords(2)) = mouth_patch;
sr_image(coords(3):coords(4),coords(1):coords(2)) = 0;
% 2) Left Eye Region
left_eye_features = ["left_eye_left_corner",...
                     "left_eye_upper_left_quarter",...
                     "left_eye_top",...
                     "left_eye_upper_right_quarter",...
                     "left_eye_right_corner",...
                     "left_eye_lower_right_quarter",...
                     "left_eye_bottom",...
                     "left_eye_lower_left_quarter",...
                     "left_eye_center",...
                     "left_eye_pupil"];
left_eyebrow_features = ["left_eyebrow_left_corner",...
                         "left_eyebrow_upper_left_quarter",...
                         "left_eyebrow_upper_middle",...
                         "left_eyebrow_upper_right_quarter",...
                         "left_eyebrow_right_corner",...
                         "left_eyebrow_lower_right_quarter",...
                         "left_eyebrow_lower_middle",...
                         "left_eyebrow_lower_left_quarter"];
left_eye_features = [left_eye_features left_eyebrow_features];
[left_eye_patch, ~, coords] = Get_SR_Patch(sr_image, left_eye_features, landmarks, dataset_landmarks, 2, 2);
patched_image(coords(3):coords(4),coords(1):coords(2)) = left_eye_patch;
sr_image(coords(3):coords(4),coords(1):coords(2)) = 0;
% 3) Right Eye Region
right_eye_features = ["right_eye_left_corner",...
                      "right_eye_upper_left_quarter",...
                      "right_eye_top",...
                      "right_eye_upper_right_quarter",...
                      "right_eye_right_corner",...
                      "right_eye_lower_right_quarter",...
                      "right_eye_bottom",...
                      "right_eye_lower_left_quarter",...
                      "right_eye_center",...
                      "right_eye_pupil"];
right_eyebrow_features = ["right_eyebrow_left_corner",...
                          "right_eyebrow_upper_left_quarter",...
                          "right_eyebrow_upper_middle",...
                          "right_eyebrow_upper_right_quarter",...
                          "right_eyebrow_right_corner",...
                          "right_eyebrow_lower_right_quarter",...
                          "right_eyebrow_lower_middle",...
                          "right_eyebrow_lower_left_quarter"];
right_eye_features = [right_eye_features right_eyebrow_features];
[right_eye_patch, ~, coords] = Get_SR_Patch(sr_image, right_eye_features, landmarks, dataset_landmarks, 2, 2);
patched_image(coords(3):coords(4),coords(1):coords(2)) = right_eye_patch;
sr_image(coords(3):coords(4),coords(1):coords(2)) = 0;
% 4) Nose Region
nose_features = ["nose_contour_left3",...
                 "nose_contour_left2",...
                 "nose_contour_left1",...
                 "nose_left",...
                 "nose_contour_lower_middle",...
                 "nose_right",...
                 "nose_contour_right1",...
                 "nose_contour_right2",...
                 "nose_contour_right3",...
                 "nose_tip"];
[nose_patch, ~, coords] = Get_SR_Patch(sr_image, nose_features, landmarks, dataset_landmarks, 5, 1);
patched_image(coords(3):coords(4),coords(1):coords(2)) = nose_patch;
sr_image(coords(3):coords(4),coords(1):coords(2)) = 0;

% Show the final patched image
patched_image = imfuse(patched_image, sr_image, 'blend', 'Scaling','joint');
imshow(patched_image);
waitforbuttonpress

end

